# DLSM_SANITIZER = address | undefined | thread | "" (none)
set(DLSM_SANITIZER "" CACHE STRING "Sanitizer: address|undefined|thread|''")
function(dlsm_apply_sanitizer target)
  if(DLSM_SANITIZER STREQUAL "")
    return()
  endif()
  target_compile_options(${target} PRIVATE -fsanitize=${DLSM_SANITIZER} -fno-omit-frame-pointer -g)
  target_link_options(${target} PRIVATE -fsanitize=${DLSM_SANITIZER})
endfunction()
